---
language: bash

dist: trusty

env:
  - VERSION=11.0-jre11-slim
  - VERSION=11.0-jre11
  - VERSION=11.0-jdk16-slim
  - VERSION=11.0-jdk16
  - VERSION=11.0-jdk11-slim
  - VERSION=11.0-jdk11
  - VERSION=10.0-jre11-slim
  - VERSION=10.0-jre11
  - VERSION=10.0-jdk16-slim
  - VERSION=10.0-jdk16
  - VERSION=10.0-jdk11-slim
  - VERSION=10.0-jdk11
  - VERSION=9.4-jre8-slim
  - VERSION=9.4-jre8
  - VERSION=9.4-jre11-slim
  - VERSION=9.4-jre11
  - VERSION=9.4-jdk8-slim
  - VERSION=9.4-jdk8
  - VERSION=9.4-jdk16-slim
  - VERSION=9.4-jdk16
  - VERSION=9.4-jdk11-slim
  - VERSION=9.4-jdk11
  - VERSION=9.3-jre8
  - VERSION=9.2-jre8

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
  - cd "${VERSION}"
  - image="jetty:${VERSION}"

script:
  - docker build --pull -t "$image" .
  - ~/official-images/test/run.sh "$image"
